### ISSUE TITLE
PR for a simple UI test for MozVPN app (iOS)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#115]

**Comment by isabelrios** [comment]
Adding the repo: https://github.com/mozilla-mobile/guardian-vpn-ios
And the draft they have created for tests, they only have one test, related to performance, not UI: https://github.com/mozilla-mobile/guardian-vpn-ios/blob/develop/FirefoxPrivateNetworkVPNUITests/FirefoxPrivateNetworkVPNUITests.swift

**Comment by isabelrios** [comment]
Looks like the project does not build on Xcode 12 yet...Scheme Lottie_iOS is failing when running command: `carthage bootstrap --platform iOS --no-use-binaries --cache-builds`

**Comment by isabelrios** [comment]
PR: https://github.com/mozilla-mobile/guardian-vpn-ios/pull/273

We would need access to the repo. I can't select reviewers or things like that...

**Comment by isabelrios** [comment]
Closing issue, PR was merged by Celeste
