### ISSUE TITLE
Time box pulling test coverage data from TestRail API via python

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#143]
https://www.gurock.com/testrail/docs/api/getting-started/binding-python

chartjes also did some work here.  Krupa may have more info

**Comment by AaronMT** [comment]
started a WIP here https://github.com/AaronMT/testrail-automation-fenix

We can decide on what sort of data we want to pull from test rail for Fenix, e.g, disabled automation? suitable?

Do we want to just have a list we occasionally publish somewhere? Etc 

The script currently authenticates with whatever username and token you provide in environment variables. The script prints out the custom automation statuses for all cases in all suites in Fenix (as an example).
