### ISSUE TITLE
Migrate FxA Sync test docs to Github

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#149]
@AaronMT where are these currently located?  Can you provide links here?
[irios] We have these gdocs with info related to FxA Sync tests: 
- [Mobile Test Eng: FxA iOS Test Automation](https://docs.google.com/document/d/1Q5w2XpjTstZnwUF3f03patNG1ZsUK_F4zc98SVpk1rM/edit#heading=h.7ch68gj0ddcy)
- [Mobile Test Eng:  Sync Integration Test info (WIP)](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/edit#heading=h.nwcilbj944w2)

**Comment by isabelrios** [comment]
I will update the doc and add the info to the wiki for Firefox and Fenix

**Comment by isabelrios** [comment]
Firefox-iOS: https://github.com/mozilla-mobile/firefox-ios/wiki/Sync-Integration-Tests, please review it and give me your feedback or modify the file directly, as you prefer

For Fenix it may be better to add it once we have the tests running again, or should we add it now? @rpappalax wdyt?
Thanks!

**Comment by isabelrios** [comment]
Let's close this and open a new one for the remaining work which is specific to Fenix when the sync tests run there
