### ISSUE TITLE
Migrate L10N docs to Github

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#150]
As the title says, this issue is to track the work to udpate/migrate the L10n docs we have to Github. See comments below for each project's status as what is being done.

**Comment by isabelrios** [comment]
Doing a bit of work related to this issue. 
On **firefox-iOS** there are a few wiki pages about l10n:
- https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshot-Tests
- https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization

The missing piece is the one related to launch the screenshots tests on CI using Taskcluster hook, seeing the builds on Bitrise and the final link with results back on Taskcluster. 
We have a gdoc with that info:
https://docs.google.com/document/d/1Fo5oLMSNzZ0M_MRhSV9Ln2OL5oP7G4AVI4eMsOTXa38/edit?usp=sharing

On **focus-iOS**: 
There is not any wiki page about L10n tests. We could add that by copying/modifying/adapting the Focus part of that doc in wiki page

On **Fenix**:
There is not any web page but there is a Doc related to L10n tests, specifically, how to run them locally. 
We could add there that there is a cron job running the l10n tests weekly to be sure they work, but not results are reported for that job. 
https://github.com/mozilla-mobile/fenix/blob/5a8a7f549946fc8ad6ccf31f8c9c6bc2180aaed2/.cron.yml#L27
[Link to treeherder job](https://treeherder.mozilla.org/jobs?repo=fenix&fromchange=67fb033f1bc8b772b64a1fda410632dd7e59450e&selectedTaskRun=NngGd-kXTtGGDpI9sMl2Bw.0)

**Comment by isabelrios** [comment]
For Firefox-iOS, I added this paragraph: https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization#running-from-xcode-locally.

Please @AaronMT @rpappalax  feel free to modify things or give me feedback so that I can do it.

**Comment by isabelrios** [comment]
Same for Focus-iOS:
https://github.com/mozilla-mobile/focus-ios/wiki/Screenshots-for-Localization
Turns out that actually there is a page about screenshots tests that I just modified. Changes are similar to the firefox ones, but happy to receive feedback/improve it

**Comment by isabelrios** [comment]
And a PR for Fenix to update the existing doc in the repo: https://github.com/mozilla-mobile/fenix/pull/22917

**Comment by isabelrios** [comment]
This is the doc where we were documenting all about these tests: https://docs.google.com/document/d/1Fo5oLMSNzZ0M_MRhSV9Ln2OL5oP7G4AVI4eMsOTXa38/edit#heading=h.qhkgsudf79w4

**Comment by isabelrios** [comment]
PR with changes for Fenix has landed already.
Changes requested by @rpappalax in iOS docs (make team and slack links) are done too.
Closing for now.
