### ISSUE TITLE
Compare cost of hosting at MacStadium vs. AWS EC2 Mac

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#156]
Purpose: Migrate Sync-testing laptop at SFO IOT lab to a cloud provider in 2021

Talk to Jeremy Orem if we can get a discount

**Comment by AaronMT** [comment]
https://aws.amazon.com/blogs/aws/new-use-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/
