### ISSUE TITLE
Support building A-S Swift library with multiple stable Xcode (Circle-CI)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#167]
https://github.com/mozilla/application-services/issues/3799

NOTE:
Wait until decision about Swift library has been made

NEXT STEPS
1. Identify a reasonable matrix (ex.  current and next A-S version x current and next stable Xcode - 2x2)
2. Setup a cron job to run weekly
3. Post a slack notification with PASS or FAIL result

**Comment by isabelrios** [comment]
See issue #300 with some comments

**Comment by isabelrios** [comment]
And also #421

**Comment by isabelrios** [comment]
Let's close for now and open a similar one on Jira if needed.
