### ISSUE TITLE
[Xcodebuild] Run builds on different Xcode and/or iOS builds on Bitrise

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#169]
At least once a week it would be good to have a build running on different Xcode versions.
Details to be defined but something to improve the Xcode build stability for iOS projects

**Comment by rpappalax** [comment]
from pdehaan:  Bitrise only indicates A.B.X versions.  A.B.x can be more than one version of Xcode depending on when they upgrade (i.e.  A.B.1,  A.B.3....).  Do we want to determine which one we are running and indicate that in our slack message?

**Comment by isabelrios** [comment]
**1. For Xcode versions:** 
I don't want to be negative with this, I may be missing things here but I don't know how we can build using different/older xcode versions.. Let me try to explain with this example...
- [Worflow using Xcode 12.0](https://app.bitrise.io/build/43c717d4d4744524#?tab=log) fails with error:
```
Skipped installing application-services.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)."
```
Same workflow works with Xcode 12.4 but fails again with Xcode 12.5 beta:
```
Skipped installing application-services.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.4 (swiftlang-1205.0.16.12 clang-1205.0.19.6)."
```

There are some compatibilities like Xcode 12.2, 12.3 and 12.4 that work building main. We can focus on those small updates having main building on each one and then add 12.5 and the followings... 

Having the NewXcodeWorkflow running, we will notice when a new one comes and when it works we can add it to the list...

**2. For iOS versions:**
This looks easier to implement. 
- The easiest: Create a workflow that have as many test steps as iOS versions we want to run the tests against. Schedule this workflow once a week for example
- Require investigation: Maybe there is an option with TC, similar to L10n tests we could build once and then launch different builds against different iOS versions

@rpappalax let's continue the discussions around this to keep working to improve the processes for iOS team

**Comment by isabelrios** [comment]
At least we should try to run the app using the very latest xcode version, and since we have a workflow for that, we could use it.
