### ISSUE TITLE
[Dashboard data query]  github  API - Firefox ios open issues

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#181]

**Comment by isabelrios** [comment]
If we want to have a trend and show how many issues were open/close per relase or sprint we would need to collect that data and then query it properly.

I have create a python script that queries github (firefox-ios and label: Bug 🐞) and stores the open/closed issues by time, so the data is shown as:

[{
    "date": "2021-01-28",
    "open": 328,
    "closed": 407
},
{
    "date": "2021-01-29",
    "open": 328,
    "closed": 407
}]
