### ISSUE TITLE
[Xcodebuild] Add Slack integration (when all other tasks are done)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#211]
Created [PR](https://github.com/mozilla-mobile/firefox-ios/pull/8004) for this

**Comment by isabelrios** [comment]
This has [landed](https://github.com/mozilla-mobile/firefox-ios/pull/8004). We can close for now and if the notification we receive in firefox-iOS channel is not what we want, we can revisit this and modify implementation.
