### ISSUE TITLE
[iOS] Set a process to go through the intermittent issues created to fix them

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#244]
We are using same label as in Fenix eng:intermittent-test to track those tests that fail from time to time but there is not a process set to pick those issues and fix the tests.
It would be good if we can have SV involved helping with this as on Fenix.

**Comment by isabelrios** [comment]
Link to the doc with the process: https://docs.google.com/document/d/102xhY4Kwr2sVITiplzr5TGfHv2ujZ6w_9BuAHkyXIq0/edit?usp=sharing

**Comment by rpappalax** [comment]
This is a great idea, Isabel!  Do you think, after we get a better idea what data we want (in a spreadsheet), that we might be able to surface this data automatically in the dashboard?  I think we already have a few (dashboard) issues open that are already in that area...
