### ISSUE TITLE
[iOS] Investigate if we can automatically create a build when there is a new A-S build

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#247]
The context for this is that it has happened many times that when trying to build a beta with newer A-S the build is broken. This usually happens right when building for release which could cause delays.

Let's investigate if there is an option to automate this process, similar to the new xcode detection and building work..

**Comment by AaronMT** [comment]
Thoughts, in similar fashion to Xcode release scripts:
- Cartfile https://github.com/mozilla-mobile/firefox-ios/blob/main/Cartfile for parsing out current A-S release
- Watch A-S repo for new tags on a scheduler
--  https://github.com/mozilla/application-services/tags
- On new tag, modify Cartfile 
- Push to a branch on a new PR
- Bitrise workflow builds/runs tests (exact same as Xcode) and outputs a Slack notification

**Comment by isabelrios** [comment]
Yeah! that sounds like a good approach!

**Comment by isabelrios** [comment]
Some progress here... 
- Easy to query github for tags, using this url: https://api.github.com/repos/mozilla/application-services/tags
- Progress to save it and also on reading Cartfile to get current a-s version on my repo (not uploaded yet but coming soon...)

Looking promising so far 🤞

**Comment by isabelrios** [comment]
Environment set up locally and working: https://github.com/isabelrios/demo-github-actions/pull/15 PR on firefox-iOS repo coming soon

**Comment by isabelrios** [comment]
This is the [PR](https://github.com/mozilla-mobile/firefox-ios/pull/8049) with all this work
