### ISSUE TITLE
Investigate if iOS can run on Firebase using different shards to help parallel testing

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#25]

**Comment by isabelrios** [comment]
Tried by uploading a zip file with the needed files to start a test run. Results: https://console.firebase.google.com/project/moz-firefox-ios-230118/testlab/histories/bh.e45d9815ddb759e1/matrices/6641837754115088159/executions/bs.9878fdc146548f83/test-cases

So far I could not try selecting different shards, tests  run on a real device.
Although looks like we could use Flank: https://github.com/Flank/flank#ios-example

A big cons I see is that the device is not using the latest version. The current one is Xcode 11.4.1/iOS 13.4.1 while on Firebase the Xcode is the latest one but not the device (which is using 13.2, two versions behind)
Not sure if test running on simulator would use the latest one, I guess so, but at the moment I dont have a way to test this. 

Other issue would be that we would need to modify the app so that it runs there, need devs and team agreed to do this modifications. But, if we see that tests run in parallel and the build/test execution decreases significantly, they may be in with the change.

**Comment by rpappalax** [comment]
firebase ios device list: https://gist.github.com/rpappalax/5a506eee550952e7681ced8787abf994

**Comment by isabelrios** [comment]
Yeah, I  see same list, latest  device is: 
iPhone XR  iOS 13.2
While we are  already using 13.4.1. But using simulator instead of real devices I guess they will have that version since they use the latest Xcode and the simulator iOS version is updated with it.
