### ISSUE TITLE
[Dashboard backend] Add data queries for Test Runs & Results (by project)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#255]
example: https://testrail.stage.mozaws.net/index.php?/runs/overview/59

**Comment by isabelrios** [comment]
Example:

We've finished testing Firefox iOS 32.0 (3841). Here are the results:

Testing status:  Yellow / DONE 

Testing Summary: Ship v32.0 (3841) but consider fixing the reported issues in the next release.

    Focus area: Smoke testing, Exploratory testing, Bug Verification.

    Smoke testing results:
        [Done] iPhone SE (14.4)
    Exploratory testing:
        iPhone 12 (14.4)
        iPhone Xr (14.4)

Reported issues:

    Outstanding issues:
        None

    Other issues:
        FXIOS-1513 ⁃ Default Browser Onboarding Card gets themes mixed up
        FXIOS-1517 ⁃ QR scan camera won't open if the app was backgrounded with an app menu open #803

Other issues encountered during testing:

    None

Verified issues:

    Backout customizable widgets #8029
    FXIOS-1512 ⁃ New Default Browser card is cut on iPhone SE 1st gen

**Comment by isabelrios** [comment]
Link as an example: https://testrail.stage.mozaws.net/index.php?/plans/view/40470
