### ISSUE TITLE
[Dashboard data query] github data - test out several queries as graphs

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#263]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/3699494/109682168-03121f80-7b33-11eb-9509-3b71598f5a97.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3699494/109682297-250ba200-7b33-11eb-8483-535d3e1b1f94.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/3699494/109682345-2e950a00-7b33-11eb-914e-9effb0ddb470.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/3699494/109682465-4b314200-7b33-11eb-82fc-308e28028c2e.png">

**Comment by rpappalax** [comment]
chart priorities over time on a line graph

**Comment by isabelrios** [comment]
@rpappalax Some examples:
-Fenix issues by feature:
![Captura de pantalla 2021-03-03 a las 14 05 58](https://user-images.githubusercontent.com/1897507/109810321-afcec880-7c29-11eb-8012-5f10bfb5ed14.png)

-Firefox-iOS issues by priority
![Captura de pantalla 2021-03-03 a las 14 07 36](https://user-images.githubusercontent.com/1897507/109810449-d55bd200-7c29-11eb-9e02-fd260849f93b.png)

**Comment by isabelrios** [comment]
> chart priorities over time on a line graph

We will need to run the script for some time to get a line graph... unless I'm missing something... if not, I will set it up in crontab...

Please see also issue #272 to improve the data we can show related to this issue

**Comment by rpappalax** [comment]
May also highlight some over/under used tags

**Comment by rpappalax** [comment]
could create a housekeeping graph of lesser used labels

**Comment by rpappalax** [comment]
[kbrosnan] could create multiple boards, 1 for issue state, 1 for product health, 1 for automation/CI reliability, etc.
