### ISSUE TITLE
[Maintenance] Re-enable tests on iPad simulator

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#277]
There is going to be work on iPad for the MR1.

We should enable tests on iPad simulator. In the past many bugs were found with them and it is really worthing having those at least in a scheduled build.

Let's try to prioritize this somehow...

**Comment by isabelrios** [comment]
These are the current tests failures for iPad 3rd generation (take into account that chron tabs is not enabled there) so many out of the 55 failures could be related to that:
https://addons-testing.bitrise.io/builds/0fd20dbeeafa5bc0/summary?status=failed

**Comment by isabelrios** [comment]
There is an easy way to get us running tests on iPad, starting with a scheduled build.
We can create an ENV for the RunAllXCUITest workflow for example. And then when scheduling the build we just need to set that variable to an iPad device. 
I will create a PR with these changes. 

If this goes well, it may be a good improvement for other workflows or other parameters than can be set as env variables and so reduce the workflows on Bitrise

**Comment by AaronMT** [comment]
Note:

A large number of the tests also require cancellation of the focus on address-bar at the start.

```        app.buttons["urlBar-cancel"].tap()```

**Comment by isabelrios** [comment]
First part to get this issue is done: [PR](https://github.com/mozilla-mobile/firefox-ios/pull/8292) to fix the screengraph has been merged and also smoketests for iPad is fixed with that

Now we have to set a workflow and schedule it to run the smoketest and start working on fixing the full test suite for iPad
