### ISSUE TITLE
[Smoke tests on release(s)] Add first set of tests to Nightly

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#289]
These are the first tests to be added to Nightly:

    

- noNetworkConnectionStartupTest
- SmokeTest#openMainMenuSettingsItemTest
- HistoryTest#visitedUrlHistoryTest
- SmokeTest#toggleSearchSuggestions
- SmokeTest#deleteCollectionTest
- SmokeTest#noHistoryInPrivateBrowsingTest

**Comment by sv-ohorvath** [comment]
Nightly tests added and now running: https://github.com/mozilla-mobile/fenix/pull/18486
I'll keep monitoring them along with the debug tests.
