### ISSUE TITLE
Measure taskcluster job failure counts

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#3]
can we break down by job type?
frequency: weekly

notes:
https://docs.google.com/document/d/1tXK0F8zy_iYBmNPHYG83EEjTd3ZMLMCfGuzHzhdKCP4/edit#heading=h.w42r7d8btlwo

**Comment by AaronMT** [comment]
Fenix Test Failures Query: https://sql.telemetry.mozilla.org/queries/70708/source#177924
Fenix: ui-test-x86 Query: https://sql.telemetry.mozilla.org/queries/71075/source#178666
Fenix: ui-test-x86 failure rate: https://sql.telemetry.mozilla.org/queries/71077/source
Fenix: fenix task durations by month: https://sql.telemetry.mozilla.org/queries/71084/source#178681

**Comment by AaronMT** [comment]
https://docs.google.com/document/d/1tXK0F8zy_iYBmNPHYG83EEjTd3ZMLMCfGuzHzhdKCP4/edit?usp=sharing

**Comment by rpappalax** [comment]
Will create an issue for next steps but this is done.  Great work
