### ISSUE TITLE
Investigate how to add A-S version to the Auto Update A-S PR and to the Slack notification

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#301]
To address concerns raised in comment: https://github.com/mozilla-mobile/firefox-ios/pull/8130#issuecomment-803898067

and to improve this process

**Comment by isabelrios** [comment]
So, after some testing locally on my repo, looks like there may be a way to have the new a-s version in the branch, commit, pr name... 

<img width="795" alt="Captura de pantalla 2021-03-22 a las 17 40 01" src="https://user-images.githubusercontent.com/1897507/112025761-c8017b80-8b35-11eb-8e92-8f6a37dcb860.png">

This way we can keep PR open or close depending on the result...and better inform about the status and the a-s version tested by a quick look at it...

**Comment by AaronMT** [comment]
Yes, it's possible to update the body as well at least [1], and labels.

```YAML
body: |
            - Updated with *today's* date
labels: |
            Do Not Merge ⛔️
```

[1] https://github.com/peter-evans/create-pull-request

(Date: date +%s)

**Comment by isabelrios** [comment]
Oh I forgot about the label! yeah, I will add that too

**Comment by isabelrios** [comment]
This has been completed and done. PR created automatically with branch named after the AS new release. 
Last PR was even merged by the team.

The only pending thing would be to clarify the `Do Not Merge` label with the team to not generate confusion around it

**Comment by rpappalax** [comment]
Just want to follow-up on the Slack notifications piece....

I'd like for all of our slack notifications to have really clean and concentrated content. Almost like a Twitter post.  The title should ideally be concise and clear and the body have a clear high-level explanation w/ a link to the details.  

Also, ideally, we'd make it so that all our slack messages have a similar template.

**Comment by isabelrios** [comment]
> Just want to follow-up on the Slack notifications piece....
> 
> I'd like for all of our slack notifications to have really clean and concentrated content. Almost like a Twitter post. The title should ideally be concise and clear and the body have a clear high-level explanation w/ a link to the details.
> 
> Also, ideally, we'd make it so that all our slack messages have a similar template.

@rpappalax yeah that would make sense. I'm going to open a task to cover the slack notification piece. It will require some thinking and work. On Bitrise we are sending slack notification only on merges on main and after jenkins jobs. For PRs that are from branches from main, it will be easy but not for PR that comes from a fork, due to security concerns exposing the webhook the notifications are not sent as in the previous scenarios... We will need to investigate how to do that.
