### ISSUE TITLE
[Maintenance] Fenix: Help fixing the UI tests for the new three dot menu

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#307]
Elise reached out to me looking for help to fix the tests for the new Three dot menu changes that are going on and modifying the menu significantly. She shared these two issues: 

-  https://github.com/mozilla-mobile/fenix/issues/17979
- https://github.com/mozilla-mobile/fenix/issues/17840

The new menu is under a feature flag that we can enable (how to will be shared by her)
Some of the tests that are failing due to the changes are already ignored or marked with TODO to be fixed...

**Comment by isabelrios** [comment]
There are also some tests broken testing features that don't have changes...

> It seems like some of the UI tests are breaking even if we didn’t change something. For example, we still have the refresh button but the test does not see it

I'm not sure what's the best approach here... 
- Identify all the tests that are going to be affected, maybe by running the tests witht the feature flag enabled?) mark and disable them and once the feature lands fix them
- ...

Please feel free to add more ideas... I think we should not block developers working on this feature with the tests... something similar has happened on iOS with features that changes the app a lot

**Comment by sv-ohorvath** [comment]
If the work is still in progress, I don't know how we could detect all tests that are/will be affected yet. 
I think the best would be for them to continue disabling what is blocking and add add it on the list on those 2 issues. When their work is finally done, we can then start fixing them.

**Comment by isabelrios** [comment]
Just to be clear, I did not mean to start fixing the tests :) while they are still developing the features it does not make sense at all. Totally agree with you

But maybe running the tests locally with the feature enable to help them identify the tests, mark then, PR to disable.. I don't know if that something we can really help with and if we should... but since she asked for help with tests I think it would be good for us to help so that they will come back to us in the future again... and they don't feel they are blocked by the tests

**Comment by sv-ohorvath** [comment]
Done in https://github.com/mozilla-mobile/fenix/pull/18957
