### ISSUE TITLE
[Database backend] create a database cleanup script

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#309]
create a cleanup script using this? (pls make sure to test it on a dummy table first)
Ideally it would use SHOW TABLES then iterate through each one and execute a delete command

NOTE: this would require that every table have a `create_at` column (which would need to be added if not already there)

**Comment by rpappalax** [comment]
Sample query:
select * from testrail_test_coverage WHERE created_at  < CURRENT_DATE - INTERVAL 14 DAY;

this will select anything 14 days or older (skipping more recent)


actual query would prob look like this:
DELETE FROM testrail_test_coverage WHERE created_at  < CURRENT_DATE - INTERVAL 90 DAY;

**Comment by AaronMT** [comment]
(@isabelrios at_date -> created_at)
```SQL
mysql> describe github_fenix_intermittent_tests;
+---------+---------+------+-----+---------+----------------+
| Field   | Type    | Null | Key | Default | Extra          |
+---------+---------+------+-----+---------+----------------+
| id      | int(11) | NO   | PRI | NULL    | auto_increment |
| open    | int(11) | NO   |     | NULL    |                |
| closed  | int(11) | NO   |     | NULL    |                |
| at_date | date    | YES  |     | NULL    |                |
+---------+---------+------+-----+---------+----------------+
```
and table songs

```SQL
mysql> describe songs;
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| song_id | int(11)      | NO   | PRI | NULL    | auto_increment |
| title   | varchar(255) | YES  |     | NULL    |                |
| artist  | varchar(255) | YES  |     | NULL    |                |
| genre   | varchar(255) | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+

**Comment by AaronMT** [comment]
```Python
$ python
>>> from myapp import db
>>> db.engine.table_names()
```

Easy function to add to ```db.py``` to get a list of tables to iterate through in a new script to craft a SQL statement to execute with a new ```delete``` function in ```db.py```.

**Comment by AaronMT** [comment]
Currently lives as cleanup.py in the test-dashboard backend directory.
