### ISSUE TITLE
[Maintenance] Create a matrix with the different tests running and when they run on Bitrise

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#321]
It would be nice to have on iOS a test matrix similar to the one we have for android to have a clear picture that we can share about the tests we have and when they run, as well as for the scheduled builds

**Comment by AaronMT** [comment]
Envisioning an easy to convey simple Markup table on the Wiki like:

As of April 2021 on Bitrise:

e.g, 
| Workflows  | When Ran | Device |
| ------------- | ------------- | ------------- |  
| SmokeTests  | Merge to ```main```  | iPad ✅ iPhone ✅

**Comment by isabelrios** [comment]
> Envisioning an easy to convey simple Markup table on the Wiki like:

I like this idea and the format! 

I have started by creating a [spreadsheet](https://docs.google.com/spreadsheets/d/1TyFkYTf7wbAHb5Eb_HlH-S8ZEZvH8rXm3TJLPEWG40I/edit?usp=sharing) and then we can copy the data in the wiki as you suggest.

The workflow to run tests on iPad is ready but I have not added to run for merge to main or PR so that we don't increase the build time and also to not add flakiness until we are sure the tests on iPad are green
