### ISSUE TITLE
Investigate tagging debug builds w/ browser.tabs.crashreporting.email

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#33]
We'd like to tag our debug builds with an email so we can identify which one of the crashes that appear in Sentry we are hitting in our test infra.  Purpose: so we have STR for user-found crashes

#9

**Comment by kbrosnan** [comment]
This preference is not included in crash reports. https://github.com/mozilla-mobile/android-components/issues/3261 exists to add email reporting. 

The other option would be to hook into the crash reporter directly so that we can annotate without using email as a hack.
