### ISSUE TITLE
[CI Infra] investigate having community contributers be able to run tests and see results

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#341]
https://www.netguru.com/codestories/how-to-tigger-bitrise-workflow-from-github-using-google-cloud-function

https://mozilla.slack.com/archives/GFECL5NH3/p1619146713058400

Current workflow is manual but with few contributors this may not be worth pursuing for now.

**Comment by isabelrios** [comment]
Not sure about this issue...currently we have the pre-approval to build on PRs for everyone, people in team and contributors. If we disable that, PRs will run for everyone. It will build and run the tests as usual.

It may be risky to have some credentials exposed directly to PRs (although they are not shown but could be accessed somehow) if we don't know who has created them... I guess it is there where we could add some logic

**Comment by isabelrios** [comment]
As per boek comment:

> I wonder if we can use actions to kickoff bitrise builds to get auto builds for verified contributors
