### ISSUE TITLE
Explore contributor pull-request Github Action workflow for UI tests on iOS

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#368]
It might be possible to setup a similar MacOS/iPhone simulator environment for contributor workflows to run a test on contributor PR's.

- https://github.com/sersoft-gmbh/xcodebuild-action/blob/master/.github/workflows/pull-request-tests.yml
- https://github.com/marketplace/actions/xcodebuild-action
- https://github.com/marketplace/actions/carthage-bootstrap (seems like some kind of wrapper; not sure if needed)

**Comment by rpappalax** [comment]
@aaronMT this would be good to have in our back pocket to know we can do it, but prob should timebox to no more than 2 hours

**Comment by AaronMT** [comment]
Turns out this is less complicated than I thought. The MacOS VM contains Carthage and Node and Xcode Command Line Tools [1]. All that's required is running ```Bootstrap.sh``` and any ```Xcodebuild``` command line

E.g, on Xcode 12.4 running the SmokeTestSuite on trigger will take about ~40min https://github.com/AaronMT/firefox-ios/runs/2530764415?check_suite_focus=true

Workflow: https://github.com/AaronMT/firefox-ios/blob/main/.github/workflows/build-contributor-pr.yml

[1] https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md

How does that compare to running this on Bitrise (@isabelrios)?
