### ISSUE TITLE
Standardize github issue labels across all mobile projects

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#37]

**Comment by rpappalax** [comment]
see: https://github.com/mozilla-mobile/reference-browser/issues/1224

**Comment by rpappalax** [comment]
@isabelrios @AaronMT I realize we only have control over the labels that relate to our automation tests.  Do we already have this accomplished?

**Comment by AaronMT** [comment]
For the labels that we use I believe we standardized them.

**Comment by rpappalax** [comment]
@rpappalax follow up w/ SV
