### ISSUE TITLE
Create Firebase key moz-focus-android

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#389]
* Delete existing moz-focus-android project
* Re-create moz-focus-android project
* Go to Firebase and select moz-focus-android project
* Verify that service account keys are created
* Use run script to verify that new service account key can talk to Firebase
* If not, add "Editor" role and re-run
* Once verified, scale back Editor permissions to only those needed

Phase 2

* Modify service account key to TaskCluster secrets format and create new secret under "project/mobile/focus-android/firebase"
* Open a branch on Focus and make sure tests run with new TaskCluster secret and new project name in script

**Comment by rpappalax** [comment]
@AaronMT I believe this is done, true?  If so, can you pls close?
