### ISSUE TITLE
Test out FullJUnitReport in Flank configuration on Fenix

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#396]
``JUnitReport.xml`` and ``FullJunitReport.xml`` are artifacts with differences. Full will include all tests results, including when tests failed and when passed on retry. This might expose more additional results for capturing as part of my Job/Push collection data on certain tasks. I think Junit report will contain one result per test. If a test fails, and then passes on retry, it will be recorded as a successful execution.

https://github.com/mozilla-mobile/fenix/pull/19897

**Comment by rpappalax** [comment]
Do you have a doc where you're beginning to architect the Job/Push data collection?  This sounds interesting but I'd like to see how this will fit into our overall strategy.  Also, if this is job/push related, does this need a dashboard or database label?

**Comment by AaronMT** [comment]
https://docs.google.com/document/d/17QsJE1jGuZGuKUXdgMOOc2Ul4obh2YcjMGLTtPDKE9I/edit?usp=sharing
