### ISSUE TITLE
Implement webdriver (web content) testing support

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#397]
DESCRIPTION
Webdriver support will enable us to add (Selenium) tests to Android projects to test for webcompat issues.

NOTES
- per etoop, webdriver support will soon be available in Geckoview.  This issue would be resolved once the proper dependencies were added either to A-C, R-B or Fenix and a simple UI (web content) test could be added using webdriver
- Work for this issue would entail setting up a first test (and framework dependencies needed).  Once an initial test is running, it could serve as a working model to add other tests
- Try out webdriver support in A-C using a sample app or in R-B

**Comment by AaronMT** [comment]
* Check in end of January with Emily's team

**Comment by rpappalax** [comment]
Closing this out in favor of: https://mozilla-hub.atlassian.net/browse/MTE-68
