### ISSUE TITLE
Add taskcluster screenshots implementation to Focus-iOS

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#399]
Issues open to track this work.
Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1716792
Github - https://github.com/mozilla-mobile/focus-ios/issues/1979https://github.com/mozilla-mobile/mobile-test-eng/issues/399
Focus-iOS - https://github.com/mozilla-mobile/focus-ios/issues/1979

**Comment by isabelrios** [comment]
Some PRs have already landed:
[l10nScreenshotsTests-add-workflow-Part1-bis](https://github.com/mozilla-mobile/focus-ios/pull/1981)
[Get Screenshots on CI: Enable Taskcluster and Taskgraph - Part 2](https://github.com/mozilla-mobile/focus-ios/pull/1978)
[For #1863 - Get Ll10n screenshots on CI - Part1 ](https://github.com/mozilla-mobile/focus-ios/pull/1966)

And according to Ben's latest comment everything is ready from TC
From our side, only one pending PR: https://github.com/mozilla-mobile/focus-ios/pull/2029

**Comment by isabelrios** [comment]
This is done. 
Important links to remember:
- Hook to trigger them: https://firefox-ci-tc.services.mozilla.com/hooks/project-releng/cron-task-mozilla-mobile-focus-ios%2Fl10-screenshots
- Link to latest screenshots: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.focus-ios.l10n-screenshots.latest

More info the the L10n Screenshot document:https://docs.google.com/document/d/1Fo5oLMSNzZ0M_MRhSV9Ln2OL5oP7G4AVI4eMsOTXa38/edit?usp=sharing
