### ISSUE TITLE
[META] Measure iOS UI test execution runtime

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#4]
Let's get these tests running either on cron job on Bitrise or using Jenkins on Mac Stadium.

On Firefox we have perf tests defined and working but not running. 

**TODO**
Decide where to run them and how often
Where to report results and how

**Comment by rpappalax** [comment]
@AaronMT afaik, we do this manually true? These number may get better or worse over time which means we either should schedule something on the calendar to measure these at a certain frequency or automate this.  What do you think?

**Comment by AaronMT** [comment]
I'm not sure if we want to look at individual test-run times for improvement or just continue to use the Job duration (start-time to end-time) from the SQL Telemetry queries to measure over time. I think the later, right? Happy to move this to Q3 triage though.

**Comment by rpappalax** [comment]
Moving to Jira: https://mozilla-hub.atlassian.net/browse/MTE-78
