### ISSUE TITLE
TaskCluster Route Notifications (Android)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#402]
We should look into adding Task notifications to Slack in the job definitions.

https://firefox-ci-tc.services.mozilla.com/docs/manual/using/task-notifications

https://firefox-ci-tc.services.mozilla.com/docs/reference/core/notify/usage

Adding an Oauth key so our bot can start posting into our workspace.  

This change will allow us to make enhancements to our existing notifications as well as add other ones.

This will enable us to add a line into our taskcluster kind configs.

WORKING: Slack text
TBD: Slack blocks

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1717500

We need to get Jeremy or someone from the CloudOps team to add the Slack Token to FirefoxCI

**Comment by rpappalax** [comment]
https://docs.google.com/document/d/1SyF9_btwKCuWGT8NNBdtBkYKLgta9-A-aRJmjNn2XvI/edit#

**Comment by AaronMT** [comment]
* Token deployed on FirefoxCI
* Next steps are adding a route https://docs.taskcluster.net/docs/reference/core/notify/usage to the job defaults on Fenix
* Test in Sandbox Slack

**Comment by AaronMT** [comment]
This is now landed for Fenix with reporting to infra alerts. I think we can use new issues for any followup.
