### ISSUE TITLE
Explore the Bitrise API

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#409]
Using the current API token (admin permissions), we should look at existing features without implementing any automation
1. build duration
2. fail/success
3. credits used for all our workflows/products - then we can analyze and optimize

Note:
Once we have a limited scope API token, we should revisit to see how we might automate

**Comment by AaronMT** [comment]
For build data we're mainly interested in the `builds` and or `build-artifact` endpoints described in doc here https://api-docs.bitrise.io

**Comment by AaronMT** [comment]
See #541
