### ISSUE TITLE
Open case for May 23 budget drop

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#428]
1. Reach out on Firebase
2. Create a case on GCP
3. Last resort, reach out to oremj

**Comment by AaronMT** [comment]
Case opened on GCP.

(07/28):  Need someone with billing role to take over
> Thank you for contacting Google Cloud Platform Billing Support. I understand you are trying to check the usage from your billing account on your Google services, unfortunately I'm unable to verify that you have a billing administrator role on the account you requested, and per our privacy policy I am unable to disclose sensitive information

**Comment by rpappalax** [comment]
@AaronMT feels like... done! true?
