### ISSUE TITLE
Talk to Fenix team about rebase policy

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#46]
https://help.github.com/en/github/administering-a-repository/configuring-commit-rebasing-for-pull-requests

(Not sure if there's more to it than the above repo setting toggle too)

Context, sometimes we push test-fixes or disable tests but then see PRs open and merges without rebase. This doesn't happen too often, but the result is that we have to drop a comment recommending a rebase and then another test-run is required with the rebase. Perhaps we can encourage a rebase policy to deter this scenario? On the other hand it's not too much to rebase, but then we see a failure prior and it requires time for us to investigate.

**Comment by sv-ohorvath** [comment]
@AaronMT We ran through the tickets in progress in the Standup meeting and decided to close this as done.
