### ISSUE TITLE
Firebase Updates - GCP: SA key record

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#463]
Create an internal Mana page for service account housekeeping

**Comment by AaronMT** [comment]
https://docs.google.com/document/d/1p-0b934oSMEQxotH9fqsUkOGugO4WajHqVsWBRclIVo/edit?usp=sharing

**Comment by rpappalax** [comment]
@AaronMT once the Mana page you've created has all the columns and desired format, would you be willing to close out this issue?
