### ISSUE TITLE
Create release UI test job notification

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#468]
Run on UI test for Nightly, Beta release builds

This currently runs on-failed in the test-infra-alerts channel. We would like this to run at all times to know when Nightly/Beta/Release passes or fails.

Since these tests run infreuqently we would like to receive a notification for either pass or failure

NOTE:
- let's initially run this in mobile-test-alerts
- if we like it, then we can ask Android team if they want it in fenix  channel
-
STEPS: 

1. Modify kind.yml to enable Slack notification
2. Slack payload should be same as current test failure notification
3. Make sure notification title is unique enough to differentiate release notifications from regular daily test notifications (so it can stand out from the others)

**Comment by AaronMT** [comment]
Example full payload definition 
https://firefox-ci-tc.services.mozilla.com/tasks/M_rJZh5BQWmhN8zhQauSWA/definition

e.g, `${task.metadata.owner} ` would output an email

This can be set to be `on-failed` https://docs.taskcluster.net/docs/reference/core/notify/usage
