### ISSUE TITLE
Fix DISABLED tests: reach out to Firebase

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#475]
Google bug: w/ Compose + IdlingResources
https://stackoverflow.com/questions/68974189/compose-espresso-link-to-become-idle-timed-out-with-jetpackcompose-lazycolumn

@AaronMT to reach out to Firebase Testlab community

See links to separate issues here:
https://github.com/mozilla-mobile/mobile-test-eng/projects/6?card_filter_query=label%3Acompose-esspresso

- swipeToSwitchTabTest
- shortcutButtonTest
- saveLoginFromPromptTest
- toggleSearchSuggestions
- openExternalLinksInPrivateTest

**Comment by AaronMT** [comment]
* saveLoginFromPromptTest
* toggleSearchSuggestions
* openExternalLinksInPrivateTest

**Comment by AndiAJ** [comment]
• swipeToSwitchTabTest
• shortcutButtonTest

**Comment by rpappalax** [comment]
shortcutButtonTest uses 
`    @get:Rule
    val activityTestRule = AndroidComposeTestRule(
        HomeActivityTestRule(),
        { it.activity }
    )`

see: https://github.com/mozilla-mobile/fenix/pull/21191/files

**Comment by rpappalax** [comment]
swipeToSwitchTabTest

[Andi] Note: no code changed, just started failing on swipe

`swipeNavBarRight(secondWebPage.url.toString())`

**Comment by rpappalax** [comment]
openExternalLinksInPrivateTest

Note: no code change

[Andi] failing here: `}.openTabDrawer {`

**Comment by rpappalax** [comment]
toggleSearchSuggestions

Task Group (yesterday of multiple ui-test-x86-debug runs on awesomebar branch) https://firefox-ci-tc.services.mozilla.com/tasks/groups/KqM6fWqmRYCAvtz4VpJx2g (edited) 

aaronmt  15:35
`java.lang.AssertionError: Failed: assertExists. 
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'mozilla firefox' (ignoreCase: false))`

**Comment by rpappalax** [comment]
saveLoginFromPromptTest

java.lang.AssertionError 
at org.junit.Assert.fail(Assert.java:87) 
at org.junit.Assert.assertTrue(Assert.java:42) 
at org.junit.Assert.assertNotNull(Assert.java:713) 
at org.junit.Assert.assertNotNull(Assert.java:723) 
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20) 
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:173) 
at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:206)
