### ISSUE TITLE
Fix DISABLED test: shortcutButtonTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#477]
shortcutButtonTest uses
@get:Rule val activityTestRule = AndroidComposeTestRule( HomeActivityTestRule(), { it.activity } )

[oana] this is only being used as a locator, and could prob be replaced w/ a UI automator locator instead

see: https://github.com/mozilla-mobile/fenix/pull/21191/files

**Comment by AndiAJ** [comment]
Fixed with [#21501](https://github.com/mozilla-mobile/fenix/pull/21501)
