### ISSUE TITLE
Fix DISABLED test: toggleSearchSuggestions

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#479]
toggleSearchSuggestions

Task Group (yesterday of multiple ui-test-x86-debug runs on awesomebar branch) https://firefox-ci-tc.services.mozilla.com/tasks/groups/KqM6fWqmRYCAvtz4VpJx2g (edited)

aaronmt 15:35
java.lang.AssertionError: Failed: assertExists. Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'mozilla firefox' (ignoreCase: false))

**Comment by AaronMT** [comment]
Failing due to refactoring of how search suggestions are displayed. It's failing on not waiting for the suggestions to come in.

Commented here https://github.com/mozilla-mobile/fenix/issues/21172

**Comment by AaronMT** [comment]
Andi has a workaround in https://github.com/mozilla-mobile/fenix/pull/21517

**Comment by AndiAJ** [comment]
Fixed with [#21517](https://github.com/mozilla-mobile/fenix/pull/21517)
