### ISSUE TITLE
Fix DISABLED test: swipeToSwitchTabTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#481]
swipeToSwitchTabTest

[Andi] Note: no code changed, just started failing on swipe

swipeNavBarRight(secondWebPage.url.toString())

**Comment by sv-ohorvath** [comment]
If I remember correctly, there were issues with the UIAutomator swipe action which accidentally clicks the element, so it might not be the solution.

Maybe it could work with the Compose API actions to swipe
https://developer.android.com/jetpack/compose/testing-cheatsheet

**Comment by sv-ohorvath** [comment]
PR is ready to land https://github.com/mozilla-mobile/fenix/pull/21444
