### ISSUE TITLE
Resolve focus-android shard timeout issue

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#482]
Change on focus has impacted test execution.

See slack convo:
https://mozilla.slack.com/archives/C4D7TER5G/p1632235419008900

Looks like the last few matrix runs have shards timing out after a half hour, and multiple end up timing out the Task

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/focus-android/pull/5436

**Comment by AaronMT** [comment]
This is fixed now.
