### ISSUE TITLE
Create a Bitrise credit usage notification (25% left)

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#490]
es via the Build List API
"credit_cost": {
    "int64": 0,
    "valid": true},

**Comment by AaronMT** [comment]
Yes via the Build List API

"credit_cost": {
    "int64": 0,
    "valid": true},

**Comment by isabelrios** [comment]
Closing as Jira ticket open: https://mozilla-hub.atlassian.net/jira/software/c/projects/MTE/boards/546?modal=detail&selectedIssue=MTE-46
