### ISSUE TITLE
INSERT daily taskcluster job data into database to track trending

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#492]

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/mobile-test-health

I read the test's in to post a Slack message here https://github.com/mozilla-mobile/mobile-test-health/blob/1d993c6f05caba5973b272cd2e98a7bc533cad2f/post.py#L81 from the large JSON dataset after querying

each `test` has a `name` and a `result` key (flaky/failure)
