### ISSUE TITLE
MKT Screenshots Focus Android

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#498]
I was pinged by Channing and Mei about getting marketing screenshots for Focus Android in these locales:
For Android: 1) ID 2) US 3) BR 4) IN 5) CN 6) MX 7) KE 8 )FR 9) GB 10) PL

https://drive.google.com/drive/folders/1HjwV3WjPJTf8dnYnWIDI1vx2hy57wjy2

@AaronMT would you be interested in working on this?

**Comment by isabelrios** [comment]
The devices required are:
Phone: 1440 × 2960
Tablet: 2400 × 3840

I have checked and emulator with those screen sizes can be created

**Comment by isabelrios** [comment]
In addition to those languages, DE will be needed using Klar instead of Focus.

**Comment by AaronMT** [comment]
1. I've reconfigured the `Screengrabfile` to point to the up to date APK paths
2. I've updated `HomeScreenRobot.kt` to not use the English strings for lookup
3. I've updated `FirstRunScreenshots.kt` to point to the Kotlin ` @Rule LocaleTestRule` 
4. @isabelrios `ID` `KE` has no strings yet?
5. Blocked on figuring out why it fails on some like 'en-US' and 'en-GB' 
```Log
[15:22:10]: Running tests for locale: en-GB
[15:22:10]: $ /Users/aaronmt/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-GB \
--no-hidden-api-checks \
-e appendTimestamp true \
-e class org.mozilla.focus.screenshots.FirstRunScreenshots \
org.mozilla.focus.debug.test/androidx.test.runner.AndroidJUnitRunner
[15:22:24]: ▸ org.mozilla.focus.screenshots.FirstRunScreenshots:.
[15:22:24]: ▸ Time: 11.199
[15:22:24]: ▸ OK (1 test)
[15:22:25]: Pulling captured screenshots for locale en-GB from the device
[15:22:25]: $ /Users/aaronmt/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[15:22:25]: ▸ /sdcard
[15:22:25]: $ /Users/aaronmt/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[15:22:25]: ▸ /data
ls: /sdcard/org.mozilla.focus.debug/screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
ls: /sdcard/Android/data/org.mozilla.focus.debug/files/screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
ls: /data/user/0/org.mozilla.focus.debug/files/org.mozilla.focus.debug/screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
ls: /data/data/org.mozilla.focus.debug/files/org.mozilla.focus.debug/screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
ls: /data/data/org.mozilla.focus.debug/app_screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
ls: /data/data/org.mozilla.focus.debug/screengrab/en-GB/images/screenshots: No such file or directory
[15:22:25]: Exit status: 1
[15:22:25]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
```
`use_tests_in_classes ['org.mozilla.focus.screenshots.FirstRunScreenshots']`
`locales ['en-GB', 'en-US', 'es-MX', 'fr', 'pl', 'pt-BR', 'in', 'id', 'zh-CN']`

**Comment by isabelrios** [comment]
Updating the issue too with my comments on slack:

>     2. I've updated `HomeScreenRobot.kt` to not use the English strings for lookup
> 

Can you please share these changes? Thanks!

>     4. @isabelrios `ID` `KE` has no strings yet?
> 

For KE it is not a locale available in the repo: https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/focus-android/l10n.toml but sometimes marketing call a locale in a different way, let me clarify that with them. ID should be available though

>     5. Blocked on figuring out why it fails on some like 'en-US' and 'en-GB'
> 

For en-GB I can reproduce the same failure but that's because looks like, according to those logs, you are using: `package org.mozilla.focus.screenshots.FirstRunScreenshots`  instead of `package org.mozilla.focus.screenshots`  not sure if you can use the first one in the Screengrabfile but if you could, it should be called as a class not as a package

**Comment by AaronMT** [comment]
Downgraded to `Successfully installed fastlane-2.186.0`  and I'm able to run different languages now.
