### ISSUE TITLE
Fix UI tests w/ VerifyPageContent

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#51]
Could verify URL instead (except refreshPageTest)

Note: see testDownloadPrompt has a separate issue

**Comment by sv-ohorvath** [comment]
I can start working on replacing the verifyPageContent where possible. 
Fixing that method is something we don't have a solution for yet.

**Comment by sv-ohorvath** [comment]
PR open: https://github.com/mozilla-mobile/fenix/pull/12499
