### ISSUE TITLE
Create a database backup / restore strategy - GCP

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#513]
DESCRIPTION

1. Review GCP's automatic backup strategy for Cloud SQL
2. Setup a backup restore mechanism
   This could easily be implemented using gcloud + cron + github actions
3. Document this strategy in Mana

REFERENCE

- https://cloud.google.com/sql/docs/mysql/backup-recovery/backups
- https://cloud.google.com/sql/docs/mysql/backup-recovery/backing-up#gcloud
- https://cloud.google.com/sql/docs/mysql/backup-recovery/restoring#restorebackups

**Comment by AaronMT** [comment]
https://cloud.google.com/sql/docs/mysql/backup-recovery/backing-up

**Comment by AaronMT** [comment]
![Screen Shot 2021-10-21 at 1 36 58 PM](https://user-images.githubusercontent.com/102331/138329029-a52defb3-eebc-4a63-a2d1-e93a94776b14.png)
