### ISSUE TITLE
Investigate using Firebase to get screenshots

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#514]
We can specify the path from where to get the screenshots.
https://github.com/mozilla-mobile/fenix/blob/main/automation/taskcluster/androidTest/flank-x86.yml#L36-L37

Note: We can communicate with Firebase to achieve the same thing.

**Comment by AaronMT** [comment]
>  A list of paths that will be copied from the device's storage to the designated results bucket after the test is complete. These must be absolute paths under /private/var/mobile/Media or /Documents of the app under test. If the path is under an app's /Documents, it must be prefixed with the app's bundle id and a colon
