### ISSUE TITLE
[META] Apply TC payload style to Jenkins notifications

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#520]
https://docs.google.com/document/d/1BIu0rTb-RKzR_p8xz4HHkHYJTo_l8Uu7fyYBZSHYTeE/edit

**Comment by AaronMT** [comment]
https://plugins.jenkins.io/slack/

> Blocks (this feature requires a 'bot user' and a custom slack app)

**Comment by AaronMT** [comment]
I think we have to create our JenkinsCI App for blocks as we are using Legacy 😵‍💫 
![Screen Shot 2021-10-25 at 3 46 39 PM](https://user-images.githubusercontent.com/102331/138760454-a8dd2f01-38ca-44ff-b92c-feca0ccdca09.png)

**Comment by isabelrios** [comment]
Closed and Jira ticket opened: https://mozilla-hub.atlassian.net/jira/software/c/projects/MTE/boards/546?modal=detail&selectedIssue=MTE-80
