### ISSUE TITLE
Apply TC payload style to Bitrise notifications

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#522]
https://docs.google.com/document/d/1BIu0rTb-RKzR_p8xz4HHkHYJTo_l8Uu7fyYBZSHYTeE/edit

**Comment by isabelrios** [comment]
I think we got something on Bitrise similar to Taskcluster notifications with the latest design:
https://mozilla.slack.com/archives/CAFC45W5A/p1640630365001000

<img width="500" alt="Captura de pantalla 2021-12-27 a las 19 51 06" src="https://user-images.githubusercontent.com/1897507/147499473-9e28fb30-3b21-4441-a54e-93dec2993fa2.png">

I think we could close this issue, wdyt @rpappalax?

**Comment by isabelrios** [comment]
Moved to review to get a reply and close or set what's missing here...
