### ISSUE TITLE
[BITRISE: BLOCKED] Bitrise API: explore to get failing tests and notify in a daily basis

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#541]
DESCRIPTION

- Similar to Taskcluster notifications, let's try to have a summary of the failing tests in a slack notification
- Waiting on a read only API token from Bitrise

- Using the current API token (admin permissions), we should look at existing features without implementing any automation
build duration
fail/success
credits used for all our workflows/products - then we can analyze and optimize
Note:
Once we have a limited scope API token, we should revisit to see how we might automate

**Comment by AaronMT** [comment]
- @isabelrios we should check with Bitrise (August, 2022)

**Comment by rpappalax** [comment]
Moved to: https://mozilla-hub.atlassian.net/browse/MTE-83?atlOrigin=eyJpIjoiMzI5MGNjNmFhMTFlNGFkNzgwZjU1MzFjNTg0MTZjNzEiLCJwIjoiaiJ9
