### ISSUE TITLE
Investigate changing system locale as pre-step in android test

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#565]
https://testrail.stage.mozaws.net/index.php?/cases/view/516079

Set language different than the system language - Investigate approach on setting a system language

**Comment by AaronMT** [comment]
I'll take a look at this this week (week of Nov 22nd)

**Comment by sv-ohorvath** [comment]
Ionut did a fix for the Focus locale test where we needed to change the system locale before the test: https://github.com/mozilla-mobile/focus-android/pull/7298/files#diff-141f18db29018b4b3de1ac2ffd2f631796768fca60d7b9972ef8038a69830d7aR157
I think we can use this approach in Fenix as well.
@AaronMT can I close this issue?

**Comment by AaronMT** [comment]
@sv-ohorvath Missed this while ago, doing triage now moving stuff to Jira. Yes, it looks like we can use that approach where we need to change locale as pre-step.
