### ISSUE TITLE
Define/stablish a process to log in holidays so that all team is aware of them (SV+Moz)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mobile-test-eng#581]
We have the mana page: https://mana.mozilla.org/wiki/display/MTE/Mobile+Test+Engineering

and the shared calendar (only used so far by Richard, Aaron and Isabel)

**Comment by rpappalax** [comment]
@isabelrios @AaronMT I think the mana page is good.  We could use our team calendar or create another one, but I think that would take up too much calendar space for everyone involved.  We're less likely to look at Mana, but we usually don't need to know PTO status all the time anyway.  Thoughts?

**Comment by isabelrios** [comment]
@rpappalax Yeah it is good, I would say, if possible for SV, to add their holidays there or to our calendar. During Xmas I was not sure who was working on their team and I think that should be clear in case something urgent comes up.
