### ISSUE TITLE
Android UI Tests: Add ability to set Gecko runtime and session prefs

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#619]
Within the application context, determine if it's possible to set Gecko runtime and Gecko session preferences, such as the case where a feature lands but is causing breakage. Can we disable said Gecko feature (i.e, a pref in `about:config`) as part of the application context in pre-setup or before test activity launches (without needing to drive UI interaction)?

In [1] there are a number of methods available for specific targeted areas, do we have to rely on these methods or can we set a preference not available through these methods? For a method not available, can we request one?

In [2] there are a couple other methods too. Do we have access to these through application context? I imagine if so, it can be a similar test helper class like setting application features (e.g, skipping onboarding). 

[1] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html
[2] https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSessionSettings.html

**Comment by AaronMT** [comment]
Adding doc label because if implemented this would benefit from doc.

**Comment by sv-ohorvath** [comment]
Created a Mana doc with the solution for this: https://mana.mozilla.org/wiki/display/MTE/Changing+GeckoView+config+preferences+in+tests

**Comment by AaronMT** [comment]
Thanks @sv-ohorvath, I'd love to have an in-test/helper solution, but this is a one avenue for ad-hoc testing off branch as it's modifying client code.

**Comment by sv-ohorvath** [comment]
Based on agi's expertise this is the only way we can change the files, in UI tests (and on remote devices):
"in your case the only way is to push a <app>-geckoview-config.yml file to the device to enable that pref, the doc is here: https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/automation.html#reading-configuration-from-a-file"
