### ISSUE TITLE
Idea: Remotely hosted and configured UI test manifest for Flank

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#620]
Idea: A remotely hosted manifest of test names that can be fed into a Flank configuration 

Problem: Each time a time meets the requirement for being disabled code needs to change in the project. This means opening a PR against the project and changing code in tests to add an `@Ignore` JUnit Annotation. What if we can do this remotely without changing project code by hosting a manifest of Class names (dynamically generated) and feeding those into the pipeline of Flank configuration at run-time (Flank configuration would look like a jumbo list of all class names since I don't believe Flank configurations can read manifests)? There would still need a a way to mark a test as ignored or skipped however.

Edit: JUnit and Flank supports `testFile` and inverse `notTestFile` https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner

**Comment by rpappalax** [comment]
This is an interesting idea!
I imagine workflow(s) would be something like this:

GIT PUSH EVENT

1. TC kicks off python script to scrape all test classes for test names
2. New flank config generated from python script (less tests in exclude file)
3. UI tests run as usual

IF...

4. A test is determined as flaky by Firebase API (If test was kicked off by a branch, DM could be sent to dev)
5. A dynamic test exclude file is updated

ASSUMPTIONS
* We maintain a config file with flaky tests to exclude
* We dynamically write a flank file with each and every single class.test_name (excluding those listed in exclude file)

**Comment by AaronMT** [comment]
Alternative angle is just having an exclude file live in project (and have Flank use `notTestFile`) and be the single source of of ignored tests instead of touching tests themselves. Might lose some context if you can't include comments in the flat file that link back to bugs.

Again, I think the idea is that I want to remove steps in the process of disabling a test, but similarly I want to make it easier to track which tests are disabled. I think a manifest could be one idea.

**Comment by AaronMT** [comment]
Closed in favour of Jira ticket https://mozilla-hub.atlassian.net/browse/MTE-90?atlOrigin=eyJpIjoiZjQ0NjIxZDczYjg2NDE5NDhjZWVjYzJlMGEwMzliMGMiLCJwIjoiaiJ9
