### ISSUE TITLE
Follow-up on camera issues on Firebase

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/mobile-test-eng#622]
Contacted the FTL support here: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1650026639123099

Some Focus test runs here on a virtual device: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7621408657853681059/details?stepId=bs.552bc4ac35023581&testCaseId=1

Same Focus tests work fine on an emulator device (ignore the failing tests in this run, they had other issues): https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6959382749916726056

Fenix: https://github.com/mozilla-mobile/fenix/issues/23298

Waiting for a follow-up on the issue of the camera not being allowed to run in the app. To enable the tests on both Fenix and Focus when we have a fix.

**Comment by sv-ohorvath** [comment]
Got a reply from a member, he asked for a more detailed log of when the permission is allowed/denied, I'll work on providing that.

**Comment by sv-ohorvath** [comment]
Got a new request to check if the issue occurs on lower APIs. Currently running the tests on API 28, 29, 30: https://github.com/mozilla-mobile/focus-android/runs/6591731714 and will send the logs to the team

**Comment by sv-ohorvath** [comment]
As it looks from [these reports](https://github.com/mozilla-mobile/fenix/issues/23298), the issues on API28 were (I assume) only audio-related tests:
rememberAllowAudioVideoPermissionChoiceTest
rememberAllowMicrophonePermissionChoiceTest
and after the API30 upgrade, all tests started to fail.
The logs from https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7592043107350156107 can also confirm that API30 has problems starting the camera, while lower APIs don't.

**Comment by sv-ohorvath** [comment]
pauldavis from FTL is still looking I guess, I sent him that report as well, no sign yet

**Comment by sv-ohorvath** [comment]
@AaronMT what do you think the following steps should be on this case?
To sum up: the permissions seem to work, but there are errors in starting the camera/mic and this seems to be specific to API 30 virtual devices. I know you've tried running tests on the Pixel2Emulator before, would that be an option?

**Comment by AaronMT** [comment]
If these tests work on API 28, we can annotate them as running on API 28 only, we can then create a separate taskgraph cron that runs them daily/weekly under a separate Flank configuration (very much like the screenshots cron) and indicate those test-targets in it so that they run.

**Comment by sv-ohorvath** [comment]
Let me try running them multiple times on API 28 and see how flaky they are,  I only checked a few times. I know the ones checking audio were problematic, but maybe I can fix that if we decide to go with your suggestion.

**Comment by sv-ohorvath** [comment]
They seem to work almost fine with API 28: https://github.com/mozilla-mobile/fenix/runs/7089587130, but the validation of page content is not working all the time: [this run for example](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8898386048716562546/details?stepId=bs.a6130a7dfc23e2a4&testCaseId=1) That maybe we can hack somehow.

**Comment by sv-ohorvath** [comment]
We decided to run the tests on API 28 on a separate cron job: https://github.com/mozilla-mobile/mobile-test-eng/issues/659 Closing this.
