### ISSUE TITLE
Firebase: Create a weekly UI test run count slack notification

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#627]

**Comment by AaronMT** [comment]
Setting up a `daily,yml` to post to infra-alerts 

Repo: https://github.com/AaronMT/firebase-mobile-data-aggregator
Action: https://github.com/AaronMT/firebase-mobile-data-aggregator/blob/main/.github/workflows/daily.yml

TODO: Work with Richard on Slack Block formatting.
