### ISSUE TITLE
SPIKE: M1 iOS Simulator 14+ copy/paste issue

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/mobile-test-eng#691]
The M1 arm64 architecture uses a wide variety of chip instruction sets that are not used in x86 or x86_64.

This has caused an issue with iOS Simulator Hypervisor starting with version 14 and beyond where a number of apis, including the copy/paste sync with Pasteboard to no longer function in non-native Webkit apps, like Firefox.

A proposed workaround to use Apple's Rosseta2 adapter to create mappings from x86_64 architecture to arm64 and arm7 does not and likely will not support the intel AVX instruction set that is, in part, responsible for this issue.

This issue is only one symptom of many issues the testing and development community are seeing with arm64 and the iOS Simulator Hypervisor.

There are some ways to work around this issue to mimic the behavior of copy/paste (a Pasteboard data seeding and import, for example), if we explicitly need to use the copy/paste action in a test.

Otherwise, if the explicit use of Pasteboard is not a testing requirement, it is recommended to continue the use of the SendKeys() api.

How the use of SendKeys() api relates to the issue of loading test HTML assets appears connected to this, however, after looking deeper into the issue, it's only incidental.

The GCDWebserver api doesn't support arm64, which results in a variety of issue, like not sending doc mime-type with server calls.

**Comment by isabelrios** [comment]
Adding the doc created to gather all the info here: 
https://docs.google.com/document/d/1SArgQxTux2taE9smlMUWxBcXlZLy5yDGeDqUEzy2pCQ/edit#heading=h.icegjp733zgt

**Comment by isabelrios** [comment]
Adding the doc created to gather all the info here: 
https://docs.google.com/document/d/1SArgQxTux2taE9smlMUWxBcXlZLy5yDGeDqUEzy2pCQ/edit#heading=h.icegjp733zgt

**Comment by isabelrios** [comment]
The information in this issue is great. We can close as we know what are the causes and possible workarounds/fixes to apply
