### ISSUE TITLE
Investigate how to automate Tracy's list e2e testcases for Sync

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#70]

**Comment by isabelrios** [comment]
This is the[ doc Tracy shared](https://docs.google.com/spreadsheets/d/1E3dKsGlNWWqXJM25Ztx71ylxSmqJWjgNmu1NG5onBDo/edit#gid=0) with us. We should look at tests starting on Line 790.

I have some rought comments to the tests in that section. @rpappalax do you want do check those before I share them? should I set up a meeting with him to start a general discussion?
