### ISSUE TITLE
Add Bitrise Step RSS release feed(s) to Slack RSS bot

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#709]
From discussion in mobile-test-ops, we should monitor releases in Bitrise Steps in-case of possible trouble with new releases, we can at least double check on the day of it a failure is related. Such as the case today where a change rolled out and affected our workflows (we currently utilize steps based pulled off of `main` branch)

@jjSDET @isabelrios 

Example we could monitor `bitrise-step-artifact-pull`

https://github.com/bitrise-steplib/bitrise-step-artifact-pull/releases.atom

Slack bot configuration:
https://mozilla.slack.com/services/B027ETFJXMZ

**Comment by rpappalax** [comment]
Closed in favor of: https://mozilla-hub.atlassian.net/browse/MTE-69
