### ISSUE TITLE
Update MappaMundi hard-coded waits to accommodate longer app load times in Bitrise

### ISSUE THREAD

**Issue by jjSDET** [mozilla-mobile/mobile-test-eng#746]
To fix flaky tests failing because app hasn't yet loaded when xcuitest runner starts.

There is a hard-coded wait of 5 seconds that needs to be updated.

A helper method in test startup() hook should also be created to verify app load state before tests begin instead of waiting on an assumption that testing is ready after an explicit wait.

I'd like to introduce more state verification and test readiness methods to receive positive confirmation that testing is ready in order to help with debugging efforts.

**Comment by isabelrios** [comment]
This is closed since PR was landed modifying the timeout for MappaMundi
