### ISSUE TITLE
Work with the Mozilla China folks to upstream features

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/mobile-test-eng#82]
There are a set of features that Mozilla China that are required for a successful launch/migration. 

* https://github.com/orgs/mozilla-mobile/projects/59

**Comment by rpappalax** [comment]
@kbrosnan is this still an in-progress task or should we move to backlog?

**Comment by kbrosnan** [comment]
This was about shipping the features the China team needed to launch. We are done here.
